version: '3.8'

services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "testpassword"
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: ./backend
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - "80:8080"
    depends_on:
      - web


volumes:
  db-data: