version: '3.8'

services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "testpassword"
    volumes:
      - ./db-data:/var/lib/postgresql/data